@echo off

start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script_Exec_PG_PROC.py public.sp_Batch_Generator('Started') > C:\MayaMaya_Python_Scripts\Parallel_log\sp_Batch_Generator_started_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script.py applied_jobs	 					                 > C:\MayaMaya_Python_Scripts\Parallel_log\applied_jobs_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script.py config_master	 					             > C:\MayaMaya_Python_Scripts\Parallel_log\config_master_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script.py coreskills_master	 				             > C:\MayaMaya_Python_Scripts\Parallel_log\coreskills_master_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script.py course_provider_master	 			             > C:\MayaMaya_Python_Scripts\Parallel_log\course_provider_master_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script.py courses_master	 					             > C:\MayaMaya_Python_Scripts\Parallel_log\courses_master_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script.py organization_subscription_plans	 	             > C:\MayaMaya_Python_Scripts\Parallel_log\organization_subscription_plans_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script.py questions_master	 				                 > C:\MayaMaya_Python_Scripts\Parallel_log\questions_master_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script.py quizs_master	 					                 > C:\MayaMaya_Python_Scripts\Parallel_log\quizs_master_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script.py skill_category_master	 			             > C:\MayaMaya_Python_Scripts\Parallel_log\skill_category_master_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script.py sprints_master	 					             > C:\MayaMaya_Python_Scripts\Parallel_log\sprints_master_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script.py subscription_coupons	 			                 > C:\MayaMaya_Python_Scripts\Parallel_log\subscription_coupons_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script.py subscription_plans	 				             > C:\MayaMaya_Python_Scripts\Parallel_log\subscription_plans_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script.py user_account	 					                 > C:\MayaMaya_Python_Scripts\Parallel_log\user_account_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script.py user_activity	 				                 > C:\MayaMaya_Python_Scripts\Parallel_log\user_activity_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script.py user_core_skills	 				                > C:\MayaMaya_Python_Scripts\Parallel_log\user_core_skills_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script.py user_courses	 					                > C:\MayaMaya_Python_Scripts\Parallel_log\user_courses_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script.py user_orgcode_history	 			                > C:\MayaMaya_Python_Scripts\Parallel_log\user_orgcode_history_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script.py user_payments	 					            > C:\MayaMaya_Python_Scripts\Parallel_log\user_payments_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script.py user_profile	 					                > C:\MayaMaya_Python_Scripts\Parallel_log\user_profile_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script.py user_questions	 					            > C:\MayaMaya_Python_Scripts\Parallel_log\user_questions_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script.py user_quizs	 						            > C:\MayaMaya_Python_Scripts\Parallel_log\user_quizs_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script.py user_results	 					                > C:\MayaMaya_Python_Scripts\Parallel_log\user_results_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script.py user_resume.chunks	 			            	> C:\MayaMaya_Python_Scripts\Parallel_log\user_resume.chunks_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script.py user_resume.files	 			            	> C:\MayaMaya_Python_Scripts\Parallel_log\user_resume.files_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script.py user_resume_and_store_link	 	            	> C:\MayaMaya_Python_Scripts\Parallel_log\user_resume_and_store_link_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script.py user_skill_results	 			            	> C:\MayaMaya_Python_Scripts\Parallel_log\user_skill_results_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script.py user_sprints	 					                > C:\MayaMaya_Python_Scripts\Parallel_log\user_sprints_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script.py user_subscription_details	 	            	> C:\MayaMaya_Python_Scripts\Parallel_log\user_subscription_details_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script.py word_association	 				                > C:\MayaMaya_Python_Scripts\Parallel_log\word_association_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script.py messages	 						                > C:\MayaMaya_Python_Scripts\Parallel_log\messages_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script.py user_resume_parsed					            > C:\MayaMaya_Python_Scripts\Parallel_log\user_resume_parsed_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\config_master.py 			  									            > C:\MayaMaya_Python_Scripts\Parallel_log\sub_config_master_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\coreskills_master.py        									            > C:\MayaMaya_Python_Scripts\Parallel_log\sub_coreskills_master_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\questions_master.py         									            > C:\MayaMaya_Python_Scripts\Parallel_log\sub_questions_master_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\skill_category_master.py    									            > C:\MayaMaya_Python_Scripts\Parallel_log\sub_skill_category_master_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\user_orgcode_history.py     									            > C:\MayaMaya_Python_Scripts\Parallel_log\sub_user_orgcode_history_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\user_profile.py             									            > C:\MayaMaya_Python_Scripts\Parallel_log\sub_user_profile_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\user_questions.py           									            > C:\MayaMaya_Python_Scripts\Parallel_log\sub_user_questions_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\user_skill_results.py       									            > C:\MayaMaya_Python_Scripts\Parallel_log\sub_user_skill_results_log.log 2>&1"   
REM Wait for 5 minutes (300 seconds)
timeout /t 300 /nobreak                                                                                          
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script_Exec_PG_PROC.py base.sp_mm_d_answer()						   > C:\MayaMaya_Python_Scripts\Parallel_log\base_sp_mm_d_answer_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script_Exec_PG_PROC.py base.sp_mm_d_course()                          > C:\MayaMaya_Python_Scripts\Parallel_log\base_sp_mm_d_course_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script_Exec_PG_PROC.py base.sp_mm_d_plan()                            > C:\MayaMaya_Python_Scripts\Parallel_log\base_sp_mm_d_plan_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script_Exec_PG_PROC.py base.sp_mm_d_question()                        > C:\MayaMaya_Python_Scripts\Parallel_log\base_sp_mm_d_question_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script_Exec_PG_PROC.py base.sp_mm_d_quiz()                            > C:\MayaMaya_Python_Scripts\Parallel_log\base_sp_mm_d_quiz_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script_Exec_PG_PROC.py base.sp_mm_d_result()                          > C:\MayaMaya_Python_Scripts\Parallel_log\base_sp_mm_d_result_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script_Exec_PG_PROC.py base.sp_mm_d_skill_category()                  > C:\MayaMaya_Python_Scripts\Parallel_log\base_sp_mm_d_skill_category_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script_Exec_PG_PROC.py base.sp_mm_d_skill_subcategory()               > C:\MayaMaya_Python_Scripts\Parallel_log\base_sp_mm_d_skill_subcategory_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script_Exec_PG_PROC.py base.sp_mm_d_sprint()                          > C:\MayaMaya_Python_Scripts\Parallel_log\base_sp_mm_d_sprint_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script_Exec_PG_PROC.py base.sp_mm_d_user()                            > C:\MayaMaya_Python_Scripts\Parallel_log\base_sp_mm_d_user_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script_Exec_PG_PROC.py base.sp_mm_f_user_counselor_notifications()    > C:\MayaMaya_Python_Scripts\Parallel_log\base_sp_mm_f_user_counselor_notifications_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script_Exec_PG_PROC.py base.sp_mm_f_user_course()                     > C:\MayaMaya_Python_Scripts\Parallel_log\base_sp_mm_f_user_course_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script_Exec_PG_PROC.py base.sp_mm_f_user_question()                   > C:\MayaMaya_Python_Scripts\Parallel_log\base_sp_mm_f_user_question_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script_Exec_PG_PROC.py base.sp_mm_f_user_quiz()                       > C:\MayaMaya_Python_Scripts\Parallel_log\base_sp_mm_f_user_quiz_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script_Exec_PG_PROC.py base.sp_mm_f_user_skill_results()              > C:\MayaMaya_Python_Scripts\Parallel_log\base_sp_mm_f_user_skill_results_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script_Exec_PG_PROC.py base.sp_mm_f_user_sprint()                     > C:\MayaMaya_Python_Scripts\Parallel_log\base_sp_mm_f_user_sprint_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script_Exec_PG_PROC.py base.sp_mm_user_activity()                     > C:\MayaMaya_Python_Scripts\Parallel_log\base_sp_mm_user_activity_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script_Exec_PG_PROC.py public.sp_Batch_Generator('Completed')         > C:\MayaMaya_Python_Scripts\Parallel_log\sp_Batch_Generator_completed_log.log 2>&1"
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Recon_Email.py 							                           > C:\MayaMaya_Python_Scripts\Parallel_log\MayaMaya_Python_Recon_Email_log.log 2>&1"
REM Wait for 5 minutes (200 seconds)
timeout /t 150 /nobreak 
start /min cmd /c "python C:\MayaMaya_Python_Scripts\MayaMaya_Python_Script_Exec_PG_PROC.py MayaMaya_DWH.sp_dwh_consolescript()          > C:\MayaMaya_Python_Scripts\Parallel_log\MayaMaya_DWH_sp_dwh_consolescript_log.log 2>&1"
